parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_mysql'
                charset: utf8mb4
                dbname: '%env(resolve:DATABASE_NAME)%'
                host: '%env(resolve:DATABASE_HOST)%'
                port: '%env(resolve:DATABASE_PORT)%'
                user: '%env(resolve:DATABASE_USER)%'
                password: '%env(resolve:DATABASE_PASSWORD)%'
            # Acalog Programs (godzilla/kingkong)
            programs:
                # configure these for your database server
                driver: 'pdo_mysql'
                charset: utf8mb4
                dbname: '%env(resolve:DATABASE_NAME_PROGRAMS)%'
                host: '%env(resolve:DATABASE_HOST_PROGRAMS)%'
                port: '%env(resolve:DATABASE_PORT_PROGRAMS)%'
                user: '%env(resolve:DATABASE_USER_PROGRAMS)%'
                password: '%env(resolve:DATABASE_PASSWORD_PROGRAMS)%'
            # DPS (godzilla/dps)
            dps:
                # configure these for your database server
                driver: 'pdo_mysql'
                charset: utf8mb4
                dbname: '%env(resolve:DATABASE_NAME_DPS)%'
                host: '%env(resolve:DATABASE_HOST_DPS)%'
                port: '%env(resolve:DATABASE_PORT_DPS)%'
                user: '%env(resolve:DATABASE_USER_DPS)%'
                password: '%env(resolve:DATABASE_PASSWORD_DPS)%'
        default_connection: default
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: default
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            # Acalog Programs (godzilla/kingkong)
            programs:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: programs
                mappings:
                    Programs:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Programs'
                        prefix: 'App\Entity\Programs'
                        alias: Programs
            # DPS (godzilla/dps)
            dps:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: dps
                mappings:
                    Dps:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/CrimeLog'
                        prefix: 'App\Entity\CrimeLog'
                        alias: dps
