# config/packages/rate_limiter.yaml
framework:
  rate_limiter:
    external_redirects:
      # use 'sliding_window' if you prefer that policy
      policy: 'fixed_window'
      limit: 5
      interval: '60 minutes'
#    authenticated_api:
#      policy: 'token_bucket'
#      limit: 5000
#      rate: { interval: '15 minutes', amount: 500 }