#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#controllers:
#    resource: '../src/Controller/'
#    type:     annotation
#
#kernel:
#    resource: '../src/Kernel.php'
#    type: attribute

#admin_users:
#    type: annotation
#    resource: App\Controller\Api\Admin\UserController
#    prefix: /api/admin/
#
#calendar:
#    type: annotation
#    resource: App\Controller\Api\CalendarController
#    prefix: /api/calendar/
#
#emails_api:
#    type: annotation
#    resource: App\Controller\Api\EmailController
#    prefix: /api/
#
#mapitems:
#    type: annotation
#    resource: App\Controller\Api\Map\MapItemController
#    prefix: /api/
#
#mapitemImages:
#    type: annotation
#    resource: App\Controller\Api\Map\MapItemImageController
#    prefix: /api/
#
#multimediaRequestAssignees:
#    type: annotation
#    resource: App\Controller\Api\MultimediaRequest\MultimediaRequestAssigneeController
#    prefix: /api/
#
#multimediaRequests:
#    type: annotation
#    resource: App\Controller\Api\MultimediaRequest\MultimediaRequestController
#    prefix: /api/
#
#redirects:
#    type: annotation
#    resource: App\Controller\Api\Redirect\RedirectController
#    prefix: /api/
#
#uncaughts:
#    type: annotation
#    resource: App\Controller\Api\Redirect\UncaughtController
#    prefix: /api/
#
#userImages:
#    type: annotation
#    resource: App\Controller\Api\UserImageController
#    prefix: /api/

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#
#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /admin/group/
