#index:
#    path: /
#    controller: App\Controller\DefaultController::index

controllers:
    resource: '../src/Controller/'
    type:     annotation

mapitems:
    type: rest
    resource: App\Controller\Api\Map\MapItemController
    prefix: /api/
