#index:
#    path: /
#    controller: App\Controller\DefaultController::index

controllers:
    resource: '../src/Controller/'
    type:     annotation

admin_users:
    type: rest
    resource: App\Controller\Api\Admin\UserController
    prefix: /api/admin/

calendar:
    type: rest
    resource: App\Controller\Api\CalendarController
    prefix: /api/calendar/

mapitems:
    type: rest
    resource: App\Controller\Api\Map\MapItemController
    prefix: /api/

mapitemImages:
    type: rest
    resource: App\Controller\Api\Map\MapItemImageController
    prefix: /api/

multimediaRequestAssignees:
    type: rest
    resource: App\Controller\Api\MultimediaRequest\MultimediaRequestAssigneeController
    prefix: /api/

multimediaRequests:
    type: rest
    resource: App\Controller\Api\MultimediaRequest\MultimediaRequestController
    prefix: /api/

redirects:
    type: rest
    resource: App\Controller\Api\Redirect\RedirectController
    prefix: /api/

userImages:
    type: rest
    resource: App\Controller\Api\UserImageController
    prefix: /api/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/group/
