app_logout:
  path: /logout
  methods: GET

####
# Use native PHP attributes instead of annotations for routes (CP 9/3/24)
####
#controllers:
#    resource: '../src/Controller/'
#    type:     annotation

admin_users:
    resource: App\Controller\Api\Admin\UserController
    prefix: /api/admin/

calendar:
    resource: App\Controller\Api\CalendarController
    prefix: /api/calendar/

emails_api:
    resource: App\Controller\Api\EmailController
    prefix: /api/

map_items:
    resource: App\Controller\Api\Map\MapItemController
    prefix: /api/

mapitemImages:
    resource: App\Controller\Api\Map\MapItemImageController
    prefix: /api/mapitemimages/

multimediaRequestAssignees:
    resource: App\Controller\Api\MultimediaRequest\MultimediaRequestAssigneeController
    prefix: /api/multimediaassignees

multimediaRequests:
    resource: App\Controller\Api\MultimediaRequest\MultimediaRequestController
    prefix: /api/multimediarequests

redirects:
    resource: App\Controller\Api\Redirect\RedirectController
    prefix: /api/redirects

uncaughts:
    resource: App\Controller\Api\Redirect\UncaughtController
    prefix: /api/uncaughts/

userImages:
    resource: App\Controller\Api\UserImageController
    prefix: /api/userimages/
